name: firebase_firestore_desktop
description: Desktop implementation of cloud_firestore
homepage: https://firebase.flutter.dev
repository: https://github.com/tanguypouriel/flutterfire_desktop
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'


dependencies:
  cloud_firestore_platform_interface: ^5.8.1
  firebase_firestore_dart:
    path: 'C:\Users\pouri\workspace\github\flutterfire_desktop\packages\firebase_firestore\firebase_firestore_dart'
  firebase_core: ^2.0.0
  firebase_core_dart: ^1.0.1
  firebase_core_desktop: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  plugin_platform_interface: ^2.1.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter: