name: firebase_firestore_dart
description: Pure Dart implementation of FlutterFire CloudFirestore API.
homepage: https://firebase.flutter.dev
repository: https://github.com/tanguypouriel/flutterfire_desktop
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  firebase_core_dart: ^1.0.1
  fixnum: ^1.0.1
  grpc: ^3.0.2
  meta: ^1.7.0
  protobuf: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
